# Generated by Django 5.0.1 on 2024-04-08 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname1', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=8, null=True)),
                ('password', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=200)),
                ('parent', models.TextField()),
                ('coin', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname2', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=6)),
                ('login', models.CharField(max_length=20)),
                ('level2', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Starter', 'Starter'), ('Designer', 'Designer')], max_length=20)),
                ('day', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('room', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
    ]
